//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/ItemListPage")]
        public string WindowsFormsApplication1_WSItemList_ItemListPage_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSItemList_ItemListPage_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/SalesOrderHeader")]
        public string WindowsFormsApplication1_WSSalkesOrderHeader_SalesOrderHeader_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalkesOrderHeader_SalesOrderHeader_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/SalesOrderLine")]
        public string WindowsFormsApplication1_WSSalesOrderLine_SalesOrderLine_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesOrderLine_SalesOrderLine_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/SalesOrderList")]
        public string WindowsFormsApplication1_WSSalesOrderList_SalesOrderList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesOrderList_SalesOrderList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Codeunit/BalanceWarehouse")]
        public string WindowsFormsApplication1_WarehouseService_BalanceWarehouse {
            get {
                return ((string)(this["WindowsFormsApplication1_WarehouseService_BalanceWarehouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/WarehouseEmployee")]
        public string WindowsFormsApplication1_WSWarehouseEmployee_WarehouseEmployee_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWarehouseEmployee_WarehouseEmployee_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/PurchaseOrderList")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_PurchaseOrderList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_PurchaseOrderList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/PickList")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_PickList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_PickList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/WarehouseReceiptLine")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_WarehouseReceiptLine_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_WarehouseReceiptLine_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/SystemService")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_SystemService {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/PurchaseOrderCard")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_PurchaseOrderCard_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_PurchaseOrderCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/UserInformation")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_UserInformation_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_UserInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/DetailedUserInformation")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_DetailedUserInformation_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_DetailedUserInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/TerminalPrinterList")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_TerminalPrinterList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_TerminalPrinterList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/PickLines")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_PickLines_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_PickLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/BinContent")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_BinContent_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_BinContent_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/WhseReceiptList")]
        public string WindowsFormsApplication1_WSTerminalPrinterList_WhseReceiptList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterList_WhseReceiptList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/TerminalPrinterList")]
        public string WindowsFormsApplication1_WSTerminalPrinterListNew_TerminalPrinterList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSTerminalPrinterListNew_TerminalPrinterList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/CustomerListPage")]
        public string WindowsFormsApplication1_WSCustomerList_CustomerListPage_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSCustomerList_CustomerListPage_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/SalesCommentLines")]
        public string WindowsFormsApplication1_WSSalesCommentLines_SalesCommentLines_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesCommentLines_SalesCommentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/SalesStatistic")]
        public string WindowsFormsApplication1_WSSalesStatistic_SalesStatistic_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesStatistic_SalesStatistic_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mail.akudim.dk:7047/UDVIKLING/WS/AKUDIM/Page/ShipmentMethodCode")]
        public string WindowsFormsApplication1_WSShipMethodCodes_ShipmentMethodCode_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSShipMethodCodes_ShipmentMethodCode_Service"]));
            }
        }
    }
}
