//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.WSSalesStatistic {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesStatistic_Binding", Namespace="urn:microsoft-dynamics-schemas/page/salesstatistic")]
    public partial class SalesStatistic_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesStatistic_Service() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_WSSalesStatistic_SalesStatistic_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SalesStatistic")]
        public SalesStatistic Read(string Document_Type, string No) {
            object[] results = this.Invoke("Read", new object[] {
                        Document_Type,
                        No});
            return ((SalesStatistic)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Document_Type, string No) {
            this.ReadAsync(Document_Type, No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Document_Type, string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Document_Type,
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SalesStatistic")]
        public SalesStatistic ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((SalesStatistic)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SalesStatistic[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] SalesStatistic_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((SalesStatistic[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SalesStatistic_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SalesStatistic_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref SalesStatistic SalesStatistic) {
            object[] results = this.Invoke("Update", new object[] {
                        SalesStatistic});
            SalesStatistic = ((SalesStatistic)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(SalesStatistic SalesStatistic) {
            this.UpdateAsync(SalesStatistic, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(SalesStatistic SalesStatistic, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        SalesStatistic}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesstatistic:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesstatistic", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref SalesStatistic[] SalesStatistic_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        SalesStatistic_List});
            SalesStatistic_List = ((SalesStatistic[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SalesStatistic[] SalesStatistic_List) {
            this.UpdateMultipleAsync(SalesStatistic_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SalesStatistic[] SalesStatistic_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        SalesStatistic_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesstatistic")]
    public partial class SalesStatistic {
        
        private string keyField;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string noField;
        
        private decimal lineAmountGeneralField;
        
        private bool lineAmountGeneralFieldSpecified;
        
        private decimal invDiscountAmount_GeneralField;
        
        private bool invDiscountAmount_GeneralFieldSpecified;
        
        private decimal totalAmount11Field;
        
        private bool totalAmount11FieldSpecified;
        
        private decimal vATAmountField;
        
        private bool vATAmountFieldSpecified;
        
        private decimal totalAmount21Field;
        
        private bool totalAmount21FieldSpecified;
        
        private decimal totalSalesLineLCY1_AmountField;
        
        private bool totalSalesLineLCY1_AmountFieldSpecified;
        
        private decimal profitLCY1Field;
        
        private bool profitLCY1FieldSpecified;
        
        private decimal adjProfitLCY1Field;
        
        private bool adjProfitLCY1FieldSpecified;
        
        private decimal profitPct1Field;
        
        private bool profitPct1FieldSpecified;
        
        private decimal adjProfitPct1Field;
        
        private bool adjProfitPct1FieldSpecified;
        
        private decimal totalSalesLine1_QuantityField;
        
        private bool totalSalesLine1_QuantityFieldSpecified;
        
        private decimal totalSalesLine1_Units_per_ParcelField;
        
        private bool totalSalesLine1_Units_per_ParcelFieldSpecified;
        
        private decimal totalSalesLine1_Net_WeightField;
        
        private bool totalSalesLine1_Net_WeightFieldSpecified;
        
        private decimal totalSalesLine1_Gross_WeightField;
        
        private bool totalSalesLine1_Gross_WeightFieldSpecified;
        
        private decimal totalSalesLine1_Unit_VolumeField;
        
        private bool totalSalesLine1_Unit_VolumeFieldSpecified;
        
        private decimal totalSalesLineLCY1_Unit_Cost_LCYField;
        
        private bool totalSalesLineLCY1_Unit_Cost_LCYFieldSpecified;
        
        private decimal totalAdjCostLCY1Field;
        
        private bool totalAdjCostLCY1FieldSpecified;
        
        private decimal totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYField;
        
        private bool totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYFieldSpecified;
        
        private int noOfVATLines_GeneralField;
        
        private bool noOfVATLines_GeneralFieldSpecified;
        
        private decimal amountInclVAT_InvoicingField;
        
        private bool amountInclVAT_InvoicingFieldSpecified;
        
        private decimal invDiscountAmount_InvoicingField;
        
        private bool invDiscountAmount_InvoicingFieldSpecified;
        
        private decimal totalInclVAT_InvoicingField;
        
        private bool totalInclVAT_InvoicingFieldSpecified;
        
        private decimal vATAmount_InvoicingField;
        
        private bool vATAmount_InvoicingFieldSpecified;
        
        private decimal totalExclVAT_InvoicingField;
        
        private bool totalExclVAT_InvoicingFieldSpecified;
        
        private decimal totalSalesLineLCY2_AmountField;
        
        private bool totalSalesLineLCY2_AmountFieldSpecified;
        
        private decimal profitLCY2Field;
        
        private bool profitLCY2FieldSpecified;
        
        private decimal adjProfitLCY2Field;
        
        private bool adjProfitLCY2FieldSpecified;
        
        private decimal profitPct2Field;
        
        private bool profitPct2FieldSpecified;
        
        private decimal adjProfitPct2Field;
        
        private bool adjProfitPct2FieldSpecified;
        
        private decimal totalSalesLine2_QuantityField;
        
        private bool totalSalesLine2_QuantityFieldSpecified;
        
        private decimal totalSalesLine2_Units_per_ParcelField;
        
        private bool totalSalesLine2_Units_per_ParcelFieldSpecified;
        
        private decimal totalSalesLine2_Net_WeightField;
        
        private bool totalSalesLine2_Net_WeightFieldSpecified;
        
        private decimal totalSalesLine2_Gross_WeightField;
        
        private bool totalSalesLine2_Gross_WeightFieldSpecified;
        
        private decimal totalSalesLine2_Unit_VolumeField;
        
        private bool totalSalesLine2_Unit_VolumeFieldSpecified;
        
        private decimal totalSalesLineLCY2_Unit_Cost_LCYField;
        
        private bool totalSalesLineLCY2_Unit_Cost_LCYFieldSpecified;
        
        private decimal totalAdjCostLCY2Field;
        
        private bool totalAdjCostLCY2FieldSpecified;
        
        private decimal totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYField;
        
        private bool totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYFieldSpecified;
        
        private int noOfVATLines_InvoicingField;
        
        private bool noOfVATLines_InvoicingFieldSpecified;
        
        private decimal totalSalesLine3_Line_AmountField;
        
        private bool totalSalesLine3_Line_AmountFieldSpecified;
        
        private decimal totalSalesLine3_Inv_Discount_AmountField;
        
        private bool totalSalesLine3_Inv_Discount_AmountFieldSpecified;
        
        private decimal totalAmount13Field;
        
        private bool totalAmount13FieldSpecified;
        
        private decimal vATAmount3Field;
        
        private bool vATAmount3FieldSpecified;
        
        private decimal totalAmount23Field;
        
        private bool totalAmount23FieldSpecified;
        
        private decimal totalSalesLineLCY3_AmountField;
        
        private bool totalSalesLineLCY3_AmountFieldSpecified;
        
        private decimal totalSalesLineLCY3_Unit_Cost_LCYField;
        
        private bool totalSalesLineLCY3_Unit_Cost_LCYFieldSpecified;
        
        private decimal profitLCY3Field;
        
        private bool profitLCY3FieldSpecified;
        
        private decimal profitPct3Field;
        
        private bool profitPct3FieldSpecified;
        
        private decimal totalSalesLine3_QuantityField;
        
        private bool totalSalesLine3_QuantityFieldSpecified;
        
        private decimal totalSalesLine3_Units_per_ParcelField;
        
        private bool totalSalesLine3_Units_per_ParcelFieldSpecified;
        
        private decimal totalSalesLine3_Net_WeightField;
        
        private bool totalSalesLine3_Net_WeightFieldSpecified;
        
        private decimal totalSalesLine3_Gross_WeightField;
        
        private bool totalSalesLine3_Gross_WeightFieldSpecified;
        
        private decimal totalSalesLine3_Unit_VolumeField;
        
        private bool totalSalesLine3_Unit_VolumeFieldSpecified;
        
        private int tempVATAmountLine3_COUNTField;
        
        private bool tempVATAmountLine3_COUNTFieldSpecified;
        
        private decimal prepmtTotalAmountField;
        
        private bool prepmtTotalAmountFieldSpecified;
        
        private decimal prepmtVATAmountField;
        
        private bool prepmtVATAmountFieldSpecified;
        
        private decimal prepmtTotalAmount2Field;
        
        private bool prepmtTotalAmount2FieldSpecified;
        
        private decimal totalSalesLine1_Prepmt_Amt_InvField;
        
        private bool totalSalesLine1_Prepmt_Amt_InvFieldSpecified;
        
        private decimal prepmtInvPctField;
        
        private bool prepmtInvPctFieldSpecified;
        
        private decimal totalSalesLine1_Prepmt_Amt_DeductedField;
        
        private bool totalSalesLine1_Prepmt_Amt_DeductedFieldSpecified;
        
        private decimal prepmtDeductedPctField;
        
        private bool prepmtDeductedPctFieldSpecified;
        
        private decimal totalSalesLine1_Prepmt_Amt_to_DeductField;
        
        private bool totalSalesLine1_Prepmt_Amt_to_DeductFieldSpecified;
        
        private int tempVATAmountLine4_COUNTField;
        
        private bool tempVATAmountLine4_COUNTFieldSpecified;
        
        private decimal cust_Balance_LCYField;
        
        private bool cust_Balance_LCYFieldSpecified;
        
        private decimal cust_Credit_Limit_LCYField;
        
        private bool cust_Credit_Limit_LCYFieldSpecified;
        
        private decimal creditLimitLCYExpendedPctField;
        
        private bool creditLimitLCYExpendedPctFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Document_Type Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified {
            get {
                return this.document_TypeFieldSpecified;
            }
            set {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public decimal LineAmountGeneral {
            get {
                return this.lineAmountGeneralField;
            }
            set {
                this.lineAmountGeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineAmountGeneralSpecified {
            get {
                return this.lineAmountGeneralFieldSpecified;
            }
            set {
                this.lineAmountGeneralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal InvDiscountAmount_General {
            get {
                return this.invDiscountAmount_GeneralField;
            }
            set {
                this.invDiscountAmount_GeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvDiscountAmount_GeneralSpecified {
            get {
                return this.invDiscountAmount_GeneralFieldSpecified;
            }
            set {
                this.invDiscountAmount_GeneralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount1[1]")]
        public decimal TotalAmount11 {
            get {
                return this.totalAmount11Field;
            }
            set {
                this.totalAmount11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmount11Specified {
            get {
                return this.totalAmount11FieldSpecified;
            }
            set {
                this.totalAmount11FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATAmountSpecified {
            get {
                return this.vATAmountFieldSpecified;
            }
            set {
                this.vATAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount2[1]")]
        public decimal TotalAmount21 {
            get {
                return this.totalAmount21Field;
            }
            set {
                this.totalAmount21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmount21Specified {
            get {
                return this.totalAmount21FieldSpecified;
            }
            set {
                this.totalAmount21FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[1]_Amount")]
        public decimal TotalSalesLineLCY1_Amount {
            get {
                return this.totalSalesLineLCY1_AmountField;
            }
            set {
                this.totalSalesLineLCY1_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY1_AmountSpecified {
            get {
                return this.totalSalesLineLCY1_AmountFieldSpecified;
            }
            set {
                this.totalSalesLineLCY1_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitLCY[1]")]
        public decimal ProfitLCY1 {
            get {
                return this.profitLCY1Field;
            }
            set {
                this.profitLCY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitLCY1Specified {
            get {
                return this.profitLCY1FieldSpecified;
            }
            set {
                this.profitLCY1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjProfitLCY[1]")]
        public decimal AdjProfitLCY1 {
            get {
                return this.adjProfitLCY1Field;
            }
            set {
                this.adjProfitLCY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjProfitLCY1Specified {
            get {
                return this.adjProfitLCY1FieldSpecified;
            }
            set {
                this.adjProfitLCY1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitPct[1]")]
        public decimal ProfitPct1 {
            get {
                return this.profitPct1Field;
            }
            set {
                this.profitPct1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitPct1Specified {
            get {
                return this.profitPct1FieldSpecified;
            }
            set {
                this.profitPct1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjProfitPct[1]")]
        public decimal AdjProfitPct1 {
            get {
                return this.adjProfitPct1Field;
            }
            set {
                this.adjProfitPct1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjProfitPct1Specified {
            get {
                return this.adjProfitPct1FieldSpecified;
            }
            set {
                this.adjProfitPct1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Quantity")]
        public decimal TotalSalesLine1_Quantity {
            get {
                return this.totalSalesLine1_QuantityField;
            }
            set {
                this.totalSalesLine1_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_QuantitySpecified {
            get {
                return this.totalSalesLine1_QuantityFieldSpecified;
            }
            set {
                this.totalSalesLine1_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Units_per_Parcel")]
        public decimal TotalSalesLine1_Units_per_Parcel {
            get {
                return this.totalSalesLine1_Units_per_ParcelField;
            }
            set {
                this.totalSalesLine1_Units_per_ParcelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Units_per_ParcelSpecified {
            get {
                return this.totalSalesLine1_Units_per_ParcelFieldSpecified;
            }
            set {
                this.totalSalesLine1_Units_per_ParcelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Net_Weight")]
        public decimal TotalSalesLine1_Net_Weight {
            get {
                return this.totalSalesLine1_Net_WeightField;
            }
            set {
                this.totalSalesLine1_Net_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Net_WeightSpecified {
            get {
                return this.totalSalesLine1_Net_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine1_Net_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Gross_Weight")]
        public decimal TotalSalesLine1_Gross_Weight {
            get {
                return this.totalSalesLine1_Gross_WeightField;
            }
            set {
                this.totalSalesLine1_Gross_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Gross_WeightSpecified {
            get {
                return this.totalSalesLine1_Gross_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine1_Gross_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Unit_Volume")]
        public decimal TotalSalesLine1_Unit_Volume {
            get {
                return this.totalSalesLine1_Unit_VolumeField;
            }
            set {
                this.totalSalesLine1_Unit_VolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Unit_VolumeSpecified {
            get {
                return this.totalSalesLine1_Unit_VolumeFieldSpecified;
            }
            set {
                this.totalSalesLine1_Unit_VolumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[1]_Unit_Cost_LCY")]
        public decimal TotalSalesLineLCY1_Unit_Cost_LCY {
            get {
                return this.totalSalesLineLCY1_Unit_Cost_LCYField;
            }
            set {
                this.totalSalesLineLCY1_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY1_Unit_Cost_LCYSpecified {
            get {
                return this.totalSalesLineLCY1_Unit_Cost_LCYFieldSpecified;
            }
            set {
                this.totalSalesLineLCY1_Unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAdjCostLCY[1]")]
        public decimal TotalAdjCostLCY1 {
            get {
                return this.totalAdjCostLCY1Field;
            }
            set {
                this.totalAdjCostLCY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdjCostLCY1Specified {
            get {
                return this.totalAdjCostLCY1FieldSpecified;
            }
            set {
                this.totalAdjCostLCY1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAdjCostLCY[1]_TotalSalesLineLCY[1]_Unit_Cost_LCY")]
        public decimal TotalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCY {
            get {
                return this.totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYField;
            }
            set {
                this.totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYSpecified {
            get {
                return this.totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYFieldSpecified;
            }
            set {
                this.totalAdjCostLCY1_TotalSalesLineLCY1_Unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NoOfVATLines_General {
            get {
                return this.noOfVATLines_GeneralField;
            }
            set {
                this.noOfVATLines_GeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfVATLines_GeneralSpecified {
            get {
                return this.noOfVATLines_GeneralFieldSpecified;
            }
            set {
                this.noOfVATLines_GeneralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountInclVAT_Invoicing {
            get {
                return this.amountInclVAT_InvoicingField;
            }
            set {
                this.amountInclVAT_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountInclVAT_InvoicingSpecified {
            get {
                return this.amountInclVAT_InvoicingFieldSpecified;
            }
            set {
                this.amountInclVAT_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal InvDiscountAmount_Invoicing {
            get {
                return this.invDiscountAmount_InvoicingField;
            }
            set {
                this.invDiscountAmount_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvDiscountAmount_InvoicingSpecified {
            get {
                return this.invDiscountAmount_InvoicingFieldSpecified;
            }
            set {
                this.invDiscountAmount_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalInclVAT_Invoicing {
            get {
                return this.totalInclVAT_InvoicingField;
            }
            set {
                this.totalInclVAT_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalInclVAT_InvoicingSpecified {
            get {
                return this.totalInclVAT_InvoicingFieldSpecified;
            }
            set {
                this.totalInclVAT_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VATAmount_Invoicing {
            get {
                return this.vATAmount_InvoicingField;
            }
            set {
                this.vATAmount_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATAmount_InvoicingSpecified {
            get {
                return this.vATAmount_InvoicingFieldSpecified;
            }
            set {
                this.vATAmount_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalExclVAT_Invoicing {
            get {
                return this.totalExclVAT_InvoicingField;
            }
            set {
                this.totalExclVAT_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalExclVAT_InvoicingSpecified {
            get {
                return this.totalExclVAT_InvoicingFieldSpecified;
            }
            set {
                this.totalExclVAT_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[2]_Amount")]
        public decimal TotalSalesLineLCY2_Amount {
            get {
                return this.totalSalesLineLCY2_AmountField;
            }
            set {
                this.totalSalesLineLCY2_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY2_AmountSpecified {
            get {
                return this.totalSalesLineLCY2_AmountFieldSpecified;
            }
            set {
                this.totalSalesLineLCY2_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitLCY[2]")]
        public decimal ProfitLCY2 {
            get {
                return this.profitLCY2Field;
            }
            set {
                this.profitLCY2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitLCY2Specified {
            get {
                return this.profitLCY2FieldSpecified;
            }
            set {
                this.profitLCY2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjProfitLCY[2]")]
        public decimal AdjProfitLCY2 {
            get {
                return this.adjProfitLCY2Field;
            }
            set {
                this.adjProfitLCY2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjProfitLCY2Specified {
            get {
                return this.adjProfitLCY2FieldSpecified;
            }
            set {
                this.adjProfitLCY2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitPct[2]")]
        public decimal ProfitPct2 {
            get {
                return this.profitPct2Field;
            }
            set {
                this.profitPct2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitPct2Specified {
            get {
                return this.profitPct2FieldSpecified;
            }
            set {
                this.profitPct2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjProfitPct[2]")]
        public decimal AdjProfitPct2 {
            get {
                return this.adjProfitPct2Field;
            }
            set {
                this.adjProfitPct2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjProfitPct2Specified {
            get {
                return this.adjProfitPct2FieldSpecified;
            }
            set {
                this.adjProfitPct2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[2]_Quantity")]
        public decimal TotalSalesLine2_Quantity {
            get {
                return this.totalSalesLine2_QuantityField;
            }
            set {
                this.totalSalesLine2_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine2_QuantitySpecified {
            get {
                return this.totalSalesLine2_QuantityFieldSpecified;
            }
            set {
                this.totalSalesLine2_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[2]_Units_per_Parcel")]
        public decimal TotalSalesLine2_Units_per_Parcel {
            get {
                return this.totalSalesLine2_Units_per_ParcelField;
            }
            set {
                this.totalSalesLine2_Units_per_ParcelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine2_Units_per_ParcelSpecified {
            get {
                return this.totalSalesLine2_Units_per_ParcelFieldSpecified;
            }
            set {
                this.totalSalesLine2_Units_per_ParcelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[2]_Net_Weight")]
        public decimal TotalSalesLine2_Net_Weight {
            get {
                return this.totalSalesLine2_Net_WeightField;
            }
            set {
                this.totalSalesLine2_Net_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine2_Net_WeightSpecified {
            get {
                return this.totalSalesLine2_Net_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine2_Net_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[2]_Gross_Weight")]
        public decimal TotalSalesLine2_Gross_Weight {
            get {
                return this.totalSalesLine2_Gross_WeightField;
            }
            set {
                this.totalSalesLine2_Gross_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine2_Gross_WeightSpecified {
            get {
                return this.totalSalesLine2_Gross_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine2_Gross_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[2]_Unit_Volume")]
        public decimal TotalSalesLine2_Unit_Volume {
            get {
                return this.totalSalesLine2_Unit_VolumeField;
            }
            set {
                this.totalSalesLine2_Unit_VolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine2_Unit_VolumeSpecified {
            get {
                return this.totalSalesLine2_Unit_VolumeFieldSpecified;
            }
            set {
                this.totalSalesLine2_Unit_VolumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[2]_Unit_Cost_LCY")]
        public decimal TotalSalesLineLCY2_Unit_Cost_LCY {
            get {
                return this.totalSalesLineLCY2_Unit_Cost_LCYField;
            }
            set {
                this.totalSalesLineLCY2_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY2_Unit_Cost_LCYSpecified {
            get {
                return this.totalSalesLineLCY2_Unit_Cost_LCYFieldSpecified;
            }
            set {
                this.totalSalesLineLCY2_Unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAdjCostLCY[2]")]
        public decimal TotalAdjCostLCY2 {
            get {
                return this.totalAdjCostLCY2Field;
            }
            set {
                this.totalAdjCostLCY2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdjCostLCY2Specified {
            get {
                return this.totalAdjCostLCY2FieldSpecified;
            }
            set {
                this.totalAdjCostLCY2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAdjCostLCY[2]_TotalSalesLineLCY[2]_Unit_Cost_LCY")]
        public decimal TotalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCY {
            get {
                return this.totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYField;
            }
            set {
                this.totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYSpecified {
            get {
                return this.totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYFieldSpecified;
            }
            set {
                this.totalAdjCostLCY2_TotalSalesLineLCY2_Unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NoOfVATLines_Invoicing {
            get {
                return this.noOfVATLines_InvoicingField;
            }
            set {
                this.noOfVATLines_InvoicingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfVATLines_InvoicingSpecified {
            get {
                return this.noOfVATLines_InvoicingFieldSpecified;
            }
            set {
                this.noOfVATLines_InvoicingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Line_Amount")]
        public decimal TotalSalesLine3_Line_Amount {
            get {
                return this.totalSalesLine3_Line_AmountField;
            }
            set {
                this.totalSalesLine3_Line_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Line_AmountSpecified {
            get {
                return this.totalSalesLine3_Line_AmountFieldSpecified;
            }
            set {
                this.totalSalesLine3_Line_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Inv_Discount_Amount")]
        public decimal TotalSalesLine3_Inv_Discount_Amount {
            get {
                return this.totalSalesLine3_Inv_Discount_AmountField;
            }
            set {
                this.totalSalesLine3_Inv_Discount_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Inv_Discount_AmountSpecified {
            get {
                return this.totalSalesLine3_Inv_Discount_AmountFieldSpecified;
            }
            set {
                this.totalSalesLine3_Inv_Discount_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount1[3]")]
        public decimal TotalAmount13 {
            get {
                return this.totalAmount13Field;
            }
            set {
                this.totalAmount13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmount13Specified {
            get {
                return this.totalAmount13FieldSpecified;
            }
            set {
                this.totalAmount13FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VATAmount[3]")]
        public decimal VATAmount3 {
            get {
                return this.vATAmount3Field;
            }
            set {
                this.vATAmount3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATAmount3Specified {
            get {
                return this.vATAmount3FieldSpecified;
            }
            set {
                this.vATAmount3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount2[3]")]
        public decimal TotalAmount23 {
            get {
                return this.totalAmount23Field;
            }
            set {
                this.totalAmount23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmount23Specified {
            get {
                return this.totalAmount23FieldSpecified;
            }
            set {
                this.totalAmount23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[3]_Amount")]
        public decimal TotalSalesLineLCY3_Amount {
            get {
                return this.totalSalesLineLCY3_AmountField;
            }
            set {
                this.totalSalesLineLCY3_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY3_AmountSpecified {
            get {
                return this.totalSalesLineLCY3_AmountFieldSpecified;
            }
            set {
                this.totalSalesLineLCY3_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLineLCY[3]_Unit_Cost_LCY")]
        public decimal TotalSalesLineLCY3_Unit_Cost_LCY {
            get {
                return this.totalSalesLineLCY3_Unit_Cost_LCYField;
            }
            set {
                this.totalSalesLineLCY3_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLineLCY3_Unit_Cost_LCYSpecified {
            get {
                return this.totalSalesLineLCY3_Unit_Cost_LCYFieldSpecified;
            }
            set {
                this.totalSalesLineLCY3_Unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitLCY[3]")]
        public decimal ProfitLCY3 {
            get {
                return this.profitLCY3Field;
            }
            set {
                this.profitLCY3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitLCY3Specified {
            get {
                return this.profitLCY3FieldSpecified;
            }
            set {
                this.profitLCY3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfitPct[3]")]
        public decimal ProfitPct3 {
            get {
                return this.profitPct3Field;
            }
            set {
                this.profitPct3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitPct3Specified {
            get {
                return this.profitPct3FieldSpecified;
            }
            set {
                this.profitPct3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Quantity")]
        public decimal TotalSalesLine3_Quantity {
            get {
                return this.totalSalesLine3_QuantityField;
            }
            set {
                this.totalSalesLine3_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_QuantitySpecified {
            get {
                return this.totalSalesLine3_QuantityFieldSpecified;
            }
            set {
                this.totalSalesLine3_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Units_per_Parcel")]
        public decimal TotalSalesLine3_Units_per_Parcel {
            get {
                return this.totalSalesLine3_Units_per_ParcelField;
            }
            set {
                this.totalSalesLine3_Units_per_ParcelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Units_per_ParcelSpecified {
            get {
                return this.totalSalesLine3_Units_per_ParcelFieldSpecified;
            }
            set {
                this.totalSalesLine3_Units_per_ParcelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Net_Weight")]
        public decimal TotalSalesLine3_Net_Weight {
            get {
                return this.totalSalesLine3_Net_WeightField;
            }
            set {
                this.totalSalesLine3_Net_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Net_WeightSpecified {
            get {
                return this.totalSalesLine3_Net_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine3_Net_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Gross_Weight")]
        public decimal TotalSalesLine3_Gross_Weight {
            get {
                return this.totalSalesLine3_Gross_WeightField;
            }
            set {
                this.totalSalesLine3_Gross_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Gross_WeightSpecified {
            get {
                return this.totalSalesLine3_Gross_WeightFieldSpecified;
            }
            set {
                this.totalSalesLine3_Gross_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[3]_Unit_Volume")]
        public decimal TotalSalesLine3_Unit_Volume {
            get {
                return this.totalSalesLine3_Unit_VolumeField;
            }
            set {
                this.totalSalesLine3_Unit_VolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine3_Unit_VolumeSpecified {
            get {
                return this.totalSalesLine3_Unit_VolumeFieldSpecified;
            }
            set {
                this.totalSalesLine3_Unit_VolumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TempVATAmountLine3_COUNT {
            get {
                return this.tempVATAmountLine3_COUNTField;
            }
            set {
                this.tempVATAmountLine3_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TempVATAmountLine3_COUNTSpecified {
            get {
                return this.tempVATAmountLine3_COUNTFieldSpecified;
            }
            set {
                this.tempVATAmountLine3_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepmtTotalAmount {
            get {
                return this.prepmtTotalAmountField;
            }
            set {
                this.prepmtTotalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepmtTotalAmountSpecified {
            get {
                return this.prepmtTotalAmountFieldSpecified;
            }
            set {
                this.prepmtTotalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepmtVATAmount {
            get {
                return this.prepmtVATAmountField;
            }
            set {
                this.prepmtVATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepmtVATAmountSpecified {
            get {
                return this.prepmtVATAmountFieldSpecified;
            }
            set {
                this.prepmtVATAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepmtTotalAmount2 {
            get {
                return this.prepmtTotalAmount2Field;
            }
            set {
                this.prepmtTotalAmount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepmtTotalAmount2Specified {
            get {
                return this.prepmtTotalAmount2FieldSpecified;
            }
            set {
                this.prepmtTotalAmount2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Prepmt_Amt_Inv")]
        public decimal TotalSalesLine1_Prepmt_Amt_Inv {
            get {
                return this.totalSalesLine1_Prepmt_Amt_InvField;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_InvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Prepmt_Amt_InvSpecified {
            get {
                return this.totalSalesLine1_Prepmt_Amt_InvFieldSpecified;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_InvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepmtInvPct {
            get {
                return this.prepmtInvPctField;
            }
            set {
                this.prepmtInvPctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepmtInvPctSpecified {
            get {
                return this.prepmtInvPctFieldSpecified;
            }
            set {
                this.prepmtInvPctFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Prepmt_Amt_Deducted")]
        public decimal TotalSalesLine1_Prepmt_Amt_Deducted {
            get {
                return this.totalSalesLine1_Prepmt_Amt_DeductedField;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_DeductedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Prepmt_Amt_DeductedSpecified {
            get {
                return this.totalSalesLine1_Prepmt_Amt_DeductedFieldSpecified;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_DeductedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepmtDeductedPct {
            get {
                return this.prepmtDeductedPctField;
            }
            set {
                this.prepmtDeductedPctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepmtDeductedPctSpecified {
            get {
                return this.prepmtDeductedPctFieldSpecified;
            }
            set {
                this.prepmtDeductedPctFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalSalesLine[1]_Prepmt_Amt_to_Deduct")]
        public decimal TotalSalesLine1_Prepmt_Amt_to_Deduct {
            get {
                return this.totalSalesLine1_Prepmt_Amt_to_DeductField;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_to_DeductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSalesLine1_Prepmt_Amt_to_DeductSpecified {
            get {
                return this.totalSalesLine1_Prepmt_Amt_to_DeductFieldSpecified;
            }
            set {
                this.totalSalesLine1_Prepmt_Amt_to_DeductFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TempVATAmountLine4_COUNT {
            get {
                return this.tempVATAmountLine4_COUNTField;
            }
            set {
                this.tempVATAmountLine4_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TempVATAmountLine4_COUNTSpecified {
            get {
                return this.tempVATAmountLine4_COUNTFieldSpecified;
            }
            set {
                this.tempVATAmountLine4_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Cust_Balance_LCY {
            get {
                return this.cust_Balance_LCYField;
            }
            set {
                this.cust_Balance_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cust_Balance_LCYSpecified {
            get {
                return this.cust_Balance_LCYFieldSpecified;
            }
            set {
                this.cust_Balance_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Cust_Credit_Limit_LCY {
            get {
                return this.cust_Credit_Limit_LCYField;
            }
            set {
                this.cust_Credit_Limit_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cust_Credit_Limit_LCYSpecified {
            get {
                return this.cust_Credit_Limit_LCYFieldSpecified;
            }
            set {
                this.cust_Credit_Limit_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CreditLimitLCYExpendedPct {
            get {
                return this.creditLimitLCYExpendedPctField;
            }
            set {
                this.creditLimitLCYExpendedPctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditLimitLCYExpendedPctSpecified {
            get {
                return this.creditLimitLCYExpendedPctFieldSpecified;
            }
            set {
                this.creditLimitLCYExpendedPctFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesstatistic")]
    public enum Document_Type {
        
        /// <remarks/>
        Quote,
        
        /// <remarks/>
        Order,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Blanket_Order,
        
        /// <remarks/>
        Return_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesstatistic")]
    public partial class SalesStatistic_Filter {
        
        private SalesStatistic_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public SalesStatistic_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesstatistic")]
    public enum SalesStatistic_Fields {
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        LineAmountGeneral,
        
        /// <remarks/>
        InvDiscountAmount_General,
        
        /// <remarks/>
        TotalAmount1_x005B_1_x005D_,
        
        /// <remarks/>
        VATAmount,
        
        /// <remarks/>
        TotalAmount2_x005B_1_x005D_,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_1_x005D__Amount,
        
        /// <remarks/>
        ProfitLCY_x005B_1_x005D_,
        
        /// <remarks/>
        AdjProfitLCY_x005B_1_x005D_,
        
        /// <remarks/>
        ProfitPct_x005B_1_x005D_,
        
        /// <remarks/>
        AdjProfitPct_x005B_1_x005D_,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Quantity,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Units_per_Parcel,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Net_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Gross_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Unit_Volume,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_1_x005D__Unit_Cost_LCY,
        
        /// <remarks/>
        TotalAdjCostLCY_x005B_1_x005D_,
        
        /// <remarks/>
        TotalAdjCostLCY_x005B_1_x005D__TotalSalesLineLCY_x005B_1_x005D__Unit_Cost_LCY,
        
        /// <remarks/>
        NoOfVATLines_General,
        
        /// <remarks/>
        AmountInclVAT_Invoicing,
        
        /// <remarks/>
        InvDiscountAmount_Invoicing,
        
        /// <remarks/>
        TotalInclVAT_Invoicing,
        
        /// <remarks/>
        VATAmount_Invoicing,
        
        /// <remarks/>
        TotalExclVAT_Invoicing,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_2_x005D__Amount,
        
        /// <remarks/>
        ProfitLCY_x005B_2_x005D_,
        
        /// <remarks/>
        AdjProfitLCY_x005B_2_x005D_,
        
        /// <remarks/>
        ProfitPct_x005B_2_x005D_,
        
        /// <remarks/>
        AdjProfitPct_x005B_2_x005D_,
        
        /// <remarks/>
        TotalSalesLine_x005B_2_x005D__Quantity,
        
        /// <remarks/>
        TotalSalesLine_x005B_2_x005D__Units_per_Parcel,
        
        /// <remarks/>
        TotalSalesLine_x005B_2_x005D__Net_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_2_x005D__Gross_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_2_x005D__Unit_Volume,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_2_x005D__Unit_Cost_LCY,
        
        /// <remarks/>
        TotalAdjCostLCY_x005B_2_x005D_,
        
        /// <remarks/>
        TotalAdjCostLCY_x005B_2_x005D__TotalSalesLineLCY_x005B_2_x005D__Unit_Cost_LCY,
        
        /// <remarks/>
        NoOfVATLines_Invoicing,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Line_Amount,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Inv_Discount_Amount,
        
        /// <remarks/>
        TotalAmount1_x005B_3_x005D_,
        
        /// <remarks/>
        VATAmount_x005B_3_x005D_,
        
        /// <remarks/>
        TotalAmount2_x005B_3_x005D_,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_3_x005D__Amount,
        
        /// <remarks/>
        TotalSalesLineLCY_x005B_3_x005D__Unit_Cost_LCY,
        
        /// <remarks/>
        ProfitLCY_x005B_3_x005D_,
        
        /// <remarks/>
        ProfitPct_x005B_3_x005D_,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Quantity,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Units_per_Parcel,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Net_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Gross_Weight,
        
        /// <remarks/>
        TotalSalesLine_x005B_3_x005D__Unit_Volume,
        
        /// <remarks/>
        TempVATAmountLine3_COUNT,
        
        /// <remarks/>
        PrepmtTotalAmount,
        
        /// <remarks/>
        PrepmtVATAmount,
        
        /// <remarks/>
        PrepmtTotalAmount2,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Prepmt_Amt_Inv,
        
        /// <remarks/>
        PrepmtInvPct,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Prepmt_Amt_Deducted,
        
        /// <remarks/>
        PrepmtDeductedPct,
        
        /// <remarks/>
        TotalSalesLine_x005B_1_x005D__Prepmt_Amt_to_Deduct,
        
        /// <remarks/>
        TempVATAmountLine4_COUNT,
        
        /// <remarks/>
        Cust_Balance_LCY,
        
        /// <remarks/>
        Cust_Credit_Limit_LCY,
        
        /// <remarks/>
        CreditLimitLCYExpendedPct,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesStatistic Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesStatistic)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesStatistic Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesStatistic)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesStatistic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesStatistic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesStatistic SalesStatistic {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesStatistic)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesStatistic[] SalesStatistic_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesStatistic[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591